-- MySQL schema
CREATE DATABASE IF NOT EXISTS notesdb;
CREATE USER IF NOT EXISTS 'notesuser'@'%' IDENTIFIED BY 'changeme';
GRANT ALL PRIVILEGES ON notesdb.* TO 'notesuser'@'%';
FLUSH PRIVILEGES;

USE notesdb;
CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
